# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='institution',
            field=models.CharField(db_index=True, help_text='Institution visited', max_length=250, null=True),
        ),
    ]
