# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='full_name',
            field=models.CharField(db_index=True, 
            help_text='Full name of visitor', max_length=250),
        ),
       # migrations.AlterField(
       #     model_name='visitor',
       #     name='institution',
       #     field=models.CharField(db_index=True, help_text='Institution visited', max_length=250, null=True),
       # ),
       # migrations.AlterField(
       #     model_name='visitor',
       #     name='modified',
       #     field=models.DateTimeField(auto_now=True, db_index=True),
       # ),
    ]
