# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_auto_20170322_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of visitor', max_length=250)),
                ('number_of_visits', models.IntegerField()),
            ],
        ),

    ]
