# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_auto_20170205_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
