# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_auto_20170205_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(db_index=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='alert',
            field=models.ManyToManyField(to='visitors.Alert'),
        ),
    ]
