# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_auto_20170520_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('number_of_visits', models.IntegerField(null=True)),
            ],
        ),
    ]
