# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_auto_20170319_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='alert',
            new_name='alerts',
        ),
    ]
