# Generated by Django 2.0.7 on 2018-07-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_subscriber_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='full_name',
            field=models.TextField(db_index=True, help_text='Full name of visitor'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='host_name',
            field=models.TextField(help_text='Name of person that receives visitor', null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='id_number',
            field=models.TextField(help_text='Id number. It should be char field as some numbers begin with zero.', null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='reason',
            field=models.TextField(help_text='Reason behind the meeting. Some peruvian institutions haveit as `observación`.', null=True),
        ),
    ]
