# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_auto_20170319_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='alerts',
            field=models.ManyToManyField(blank=True, to='visitors.Alert'),
        ),
    ]
