# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0009_alertdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='full_name',
            field=models.CharField(db_index=True, help_text='Full name of visitor', max_length=250),
        ),
    ]
