# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_auto_20170325_0254'),
        ('visitors', '0011_alert_created'),
    ]

    operations = [
    ]
