# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0012_merge_20170508_0618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
