# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-15 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='credits',
            field=models.IntegerField(null=True),
        ),
    ]
