# Generated by Django 2.0.7 on 2018-07-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_visitor_host_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='sha1',
            field=models.CharField(db_index=True, help_text='Use it as identifier for any record regardless oforigin. It is built with: date + id_number + time_start', max_length=40, null=True),
        ),
    ]
