# Generated by Django 3.1.1 on 2020-09-25 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0008_auto_20180729_2217'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE visitors_visitor ADD COLUMN full_name_dni tsvector"),
        migrations.RunSQL(
            "UPDATE visitors_visitor SET full_name_dni = to_tsvector(full_name | | ' ' | | id_number)"),  # noqa
    ]
