# Generated by Django 3.1.1 on 2020-09-25 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0009_auto_20200925_0315'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS  full_name_dni_idx ON visitors_visitor USING GIN("
            "full_name_dni)"),
    ]
