# Generated by Django 3.1.1 on 2020-09-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0010_auto_20200925_0318'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE visitors_visitor DROP COLUMN full_name_dni",
            reverse_sql="ALTER TABLE visitors_visitor ADD COLUMN full_name_dni tsvector"),
    ]
