# Generated by Django 3.1.1 on 2020-09-27 10:18

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
from django.contrib.postgres.search import SearchVector


def update_full_name_dni(apps, schema_editor):
    model = apps.get_model('visitors', 'Visitor')
    model.objects.update(full_name_dni=SearchVector('full_name', 'id_number'))


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0011_manual_remove_full_name_dni_query_20200927_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='full_name_dni',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.RunPython(update_full_name_dni, reverse_code=migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='visitor',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full_name_dni'], name='full_name_dni_idx'),
        ),
    ]
