# Generated by Django 3.1.1 on 2020-11-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0011_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='avatar_image_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
