# Generated by Django 3.1.1 on 2020-11-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0013_auto_20201121_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='full_name_dni_host_name',
        ),
    ]
