# Generated by Django 3.1.1 on 2020-11-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0014_remove_visitor_full_name_dni_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='visitor_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
