# Generated by Django 3.1.1 on 2020-11-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0015_statistic_visitor_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='visitor_count',
            field=models.IntegerField(null=True),
        ),
    ]
