# Generated by Django 3.1.1 on 2020-11-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0017_auto_20201127_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
