# Generated by Django 5.1.3 on 2025-06-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("visitors", "0020_institution"),
        ("visitors", "0021_statistic_updated_institutions"),
        ("visitors", "0022_auto_20201212_1645"),
        ("visitors", "0023_auto_20201213_1005"),
        ("visitors", "0024_auto_20210903_2339"),
        ("visitors", "0025_auto_20210908_1641"),
        ("visitors", "0026_developer_project_leader"),
        ("visitors", "0027_institution_font_awesome_icon"),
        ("visitors", "0028_visitor_institution2"),
        ("visitors", "0029_institution_ruc"),
    ]

    dependencies = [
        ("visitors", "0019_auto_20201206_0403"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorScrapeProgress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("visitor_count", models.IntegerField()),
                ("cutoff_date", models.DateField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name="statistic",
            name="updated_institutions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="created",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="modified",
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name="developer",
            name="project_leader",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.CharField(max_length=200, unique=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("rank", models.IntegerField(default=0)),
                ("font_awesome_icon", models.CharField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="visitor",
            name="institution2",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="visitors.institution"
            ),
        ),
    ]
