# Generated by Django 2.2.13 on 2020-12-06 18:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0020_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='updated_institutions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
