# Generated by Django 3.1.4 on 2021-09-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0023_auto_20201213_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
