# Generated by Django 3.1.4 on 2021-09-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0024_auto_20210903_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
