# Generated by Django 5.1.3 on 2024-11-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0026_developer_project_leader"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="font_awesome_icon",
            field=models.CharField(null=True),
        ),
    ]
