# Generated by Django 5.1.3 on 2025-02-09 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0027_institution_font_awesome_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="institution2",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="visitors.institution"
            ),
        ),
    ]
