# Generated by Django 5.1.3 on 2025-04-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0030_auto_20250209_0955"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(fields=["institution2"], name="institution2_idx"),
        ),
    ]
