# Generated by Django 5.2.2 on 2025-06-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0032_visitor_institution2_not_null_idx"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="institution",
        #     name="ruc",
        #     field=models.CharField(max_length=200, null=True, unique=True),
        # ),
        migrations.AddField(
            model_name="visitor",
            name="censored",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If True, the visitor is not shown in the search results.",
            ),
        ),
    ]
