# Generated by Django 5.2.2 on 2025-06-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0033_institution_ruc_visitor_censored"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="institution",
        #     name="ruc",
        #     field=models.CharField(max_length=200, null=True, unique=True),
        # ),
    ]
