# Generated by Django 5.2.2 on 2025-06-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0035_knowncandidate_institution_ruc"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="is_candidate",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
