# Generated by Django 5.2.2 on 2025-08-10 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0036_institution_ruc_visitor_is_candidate"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="institution",
        #     name="ruc",
        #     field=models.CharField(max_length=200, null=True, unique=True),
        # ),
    ]
