FROM manolo/manolo_app

COPY docker/cron/run_scraper_ambiente.sh /etc/cron.daily/run_scraper_ambiente.sh
RUN chmod a+x /etc/cron.daily/run_scraper_ambiente.sh

COPY docker/cron/run_scraper_congreso.sh /etc/cron.daily/run_scraper_congreso.sh
RUN chmod a+x /etc/cron.daily/run_scraper_congreso.sh

COPY docker/cron/run_scraper_defensa.sh /etc/cron.daily/run_scraper_defensa.sh
RUN chmod a+x /etc/cron.daily/run_scraper_defensa.sh

COPY docker/cron/run_scraper_ingemmet.sh /etc/cron.daily/run_scraper_ingemmet.sh
RUN chmod a+x /etc/cron.daily/run_scraper_ingemmet.sh

COPY docker/cron/run_scraper_minagr.sh /etc/cron.daily/run_scraper_minagr.sh
RUN chmod a+x /etc/cron.daily/run_scraper_minagr.sh

COPY docker/cron/run_scraper_mincu.sh /etc/cron.daily/run_scraper_mincu.sh
RUN chmod a+x /etc/cron.daily/run_scraper_mincu.sh

COPY docker/cron/run_scraper_minem.sh /etc/cron.daily/run_scraper_minem.sh
RUN chmod a+x /etc/cron.daily/run_scraper_minem.sh

COPY docker/cron/run_scraper_minsa.sh /etc/cron.daily/run_scraper_minsa.sh
RUN chmod a+x /etc/cron.daily/run_scraper_minsa.sh

COPY docker/cron/run_scraper_pcm.sh /etc/cron.daily/run_scraper_pcm.sh
RUN chmod a+x /etc/cron.daily/run_scraper_pcm.sh

COPY docker/cron/run_scraper_presidencia.sh /etc/cron.daily/run_scraper_presidencia.sh
RUN chmod a+x /etc/cron.daily/run_scraper_presidencia.sh

COPY docker/cron/run_scraper_minvi.sh /etc/cron.daily/run_scraper_minvi.sh
RUN chmod a+x /etc/cron.daily/run_scraper_minvi.sh

COPY docker/cron/run_scraper_minedu.sh /etc/cron.daily/run_scraper_minedu.sh
RUN chmod a+x /etc/cron.daily/run_scraper_minedu.sh

COPY docker/cron/run_scraper_produce2.sh /etc/cron.daily/run_scraper_produce2.sh
RUN chmod a+x /etc/cron.daily/run_scraper_produce2.sh

COPY docker/cron/run_scraper_inpe.sh /etc/cron.daily/run_scraper_inpe.sh
RUN chmod a+x /etc/cron.daily/run_scraper_inpe.sh

COPY docker/cron/run_scraper_mincetur.sh /etc/cron.daily/run_scraper_mincetur.sh
RUN chmod a+x /etc/cron.daily/run_scraper_mincetur.sh

COPY docker/cron/run_scraper_osce.sh /etc/cron.daily/run_scraper_osce.sh
RUN chmod a+x /etc/cron.daily/run_scraper_osce.sh

COPY docker/cron/run_all_scrapers.sh /etc/cron.daily/run_all_scrapers.sh
RUN chmod a+x /etc/cron.daily/run_all_scrapers.sh
