# Generated by Django 5.2.2 on 2025-08-10 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("visitors", "0037_institution_ruc"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("records_scraped", models.PositiveIntegerField(default=0)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data_hash", models.CharField(blank=True, max_length=64)),
                ("file_size_bytes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraping_periods",
                        to="visitors.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date", "institution__name"],
                "indexes": [
                    models.Index(
                        fields=["status", "start_date"], name="tracker_scr_status_c7ecc1_idx"
                    ),
                    models.Index(
                        fields=["institution", "status"], name="tracker_scr_institu_292250_idx"
                    ),
                ],
                "unique_together": {("institution", "start_date", "end_date")},
            },
        ),
    ]
